# Generated by Django 4.2.6 on 2023-12-22 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminario_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inscrito',
            old_name='id_institucion',
            new_name='institucion',
        ),
        migrations.AlterField(
            model_name='inscrito',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
