# Generated by Django 4.2.6 on 2023-12-22 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seminario_app', '0002_rename_id_institucion_inscrito_institucion_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Inscrito',
            new_name='Participante',
        ),
    ]
